class_name Enums
enum Type {NOTHING, ENERGY, FOOD, METAL, OXYGEN}
enum UnitType {INFANTRY, ARMORED_TRANSPORT, CHOPPER, FIGHTER, LOGI_TRUCK, MISSILE_TRUCK,
					ROCKET_INFANTRY, SUBMARINE, TANK, TRANSPORT_BOAT, TRANSPORT_CHOPPER,
					TRANSPORT_TRUCK, WARSHIP
				}
